#!/usr/bin/ruby
#
# This script is used to analyze git diff patches generated by "git diff commit1..commit2" command.
# Use it like this:
#
#   git diff commit1..commit2 > my.diff
#   analyze-git-diff.rb my.diff
#
# Author::  Santa Zhang (santa1987@gmail.com)
# Since::   0.3

if ARGV.length == 0
  puts "This script is used to analyze git diff patches."
  puts "Use it like this:"
  puts ""
  puts "  git diff commit1..commit2 > my.diff"
  puts "  analyze-git-diff.rb my.diff"
end

dfname = ARGV[0]

lines_add = nil
lines_del = nil
file_a = nil
File.read(dfname).each_line do |line|
  line = line.chomp
  if line.start_with? "---" or line.start_with? "+++"
    if file_a == nil
      file_a = line[4..-1]
      file_a = file_a[2..-1] unless file_a.start_with? "/dev/null"
      if lines_add != nil and lines_del != nil
        puts "#{lines_add}+\t#{lines_del}-"
      end
      lines_add = 0
      lines_del = 0
      print file_a
    else
      file_b = line[4..-1]
      file_b = file_b[2..-1] unless file_b.start_with? "/dev/null"
      if file_a != file_b
        print " => " + file_b
      end
      print "\t\t"
      file_a = nil
    end
  elsif line.start_with? "+"
    lines_add = 0 if lines_add == nil
    lines_del = 0 if lines_del == nil
    lines_add += 1
  elsif line.start_with? "-"
    lines_add = 0 if lines_add == nil
    lines_del = 0 if lines_del == nil
    lines_del += 1
  end
end

if lines_add != nil and lines_del != nil
  puts "#{lines_add}+\t#{lines_del}-"
end

