// WARNING! This file is automatically generated by "rake gen".
// WARNING! Any modification to it would be lost after another "rake gen" operation!

// Automatically generated at Tue Dec 01 13:24:15 +0800 2009

#ifndef NDSS_H_
#define NDSS_H_


#endif
