// WARNING! This file is automatically generated by "rake gen".
// WARNING! Any modification to it would be lost after another "rake gen" operation!

// Automatically generated at Tue Dec 01 14:25:24 +0800 2009

#ifndef XDK_H_
#define XDK_H_

#include "xstring.h"
#include "xmemory.h"
#include "xhash.h"

#endif
