all: ftp_server_files_list_updater

ftp_server_files_list_updater: ftp_server_files_list_updater.c
	gcc ftp_server_files_list_updater.c -o ftp_server_files_list_updater

clean:
	rm -f ftp_server_files_list_updater

