#!/usr/bin/python

# this file is used to generate test data in Nova

from urllib2 import *

import os

import json

str = os.popen("ifconfig | grep 'inet addr' | awk '{print $2}'").read().split('\n')[0]
ip = str[str.find(':') + 1:]

# ip = "localhost"

def invoke(rest):
  global ip
  url = "http://%s:3000/%s" % (ip, rest)
  print "Invoking", url
  u = urlopen(url)
  ret = u.read()
  print ret
  print # new line
  return json.loads(ret)
  
invoke("vmachine/start/v5")
invoke("vmachine/stop/v5")
invoke("vmachine/notify_status_change/v5/not%20running")

