--- 
:backgroundrb: 
  :ip: 0.0.0.0
  :port: 11006
  :environment: production

:schedules:

#  :vmachines_worker:
#    :supervise:
#      :trigger_args: */5 * * * * * 
#    :update:
#      :trigger_args: 0 */2 * * * * 

  :image_pool_worker:
    :ensure_image_pool_size:
      :trigger_args: 0 */1 * * * *

  :supervisor_worker:
    :remove_stale_files:
      :trigger_args: */5 * * * * *
    :check_copying:
      :trigger_args: 0 */1 * * * *
    :check_md5sum:
      :trigger_args: 0 0 0 */1 * *
    :update_server_image_list:
      :trigger_args: 0 */2 * * * *

