--- 
:backgroundrb: 
  :ip: 0.0.0.0
  :port: 11006
  :environment: production

:schedules:
  :vmachines_worker:
    :supervise:
      :trigger_args: */5 * * * * * 
    :update:
      :trigger_args: 0 */2 * * * * 
