CEIL_ISO_FILENAME_SERVERS = 'servers.conf'
CEIL_ISO_FILENAME_NETWORK = 'network.conf'
CEIL_ISO_FILENAME_CLUSTER = 'cluster.conf'
CEIL_ISO_FILENAME_NODELIST = 'node.list'
CEIL_ISO_FILENAME_SOFTLIST = 'soft.list'

CEIL_ISO_CONFIG_PATH = '/config'
