# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

namespace :nova do
  namespace :master do

    desc "Start Nova master (Development mode)"
    task :devstart do
      puts "Starting Nova master in *Development* mode..."
      `script/server -d`
    end

    desc "Start Nova master (Release mode)"
    task :start do
      puts "Starting Nova master in *Release* mode..."
      puts "TODO"
    end

    desc "Stop Nova server"
    task :stop do
      
      if File.exists? "tmp/pids/server.pid"
        puts "Found tmp/pids/server.pid file"
        puts "Nova master server pid = #{File.read 'tmp/pids/server.pid'}"
        puts "Terminating..."
        `kill #{File.read "tmp/pids/server.pid"}`
      end
      
      `killall mongrel`
      `killall swiftiply`
      `killall swiftiply_mongrel_rails`
      `killall mongrel_reals`
      `rm -rf log/*.pid`

    end

    desc "Initialize system"
    task :init do
      `rake db:migrate RAILS_ENV=production`
      `rake db:migrate RAILS_ENV=development`
      `rake db:migrate:reset RAILS_ENV=production`
      `rake db:migrate:reset RAILS_ENV=development`
      `rake db:fixtures:load RAILS_ENV=production`
      `rake db:fixtures:load RAILS_ENV=development`
    end

  end
end

