require File.dirname(__FILE__) + "/lib/utils.rb"
require File.dirname(__FILE__) + "/lib/gen_node_yaml.rb"
require File.dirname(__FILE__) + "/lib/install_server.rb"
require File.dirname(__FILE__) + "/lib/ssh_nopass.rb"
require File.dirname(__FILE__) + "/lib/clean_ssh_nopass.rb"
require File.dirname(__FILE__) + "/lib/create_br.rb"

desc "Show brief intro"
task :about do
  puts "rake about: show this message"
  puts "rake help: show this message"
  puts "Use 'rake -T' to get full command list"
end

namespace :check do

  desc "Do health checking on current system"
  task :health do
    puts "TODO"
  end

  desc "Check if installed"
  task :installed do
    puts "TODO"
  end

  desc "Check disk usage"
  task :du do
    puts "TODO"
  end

end

namespace :clean do

  desc "Clean up log files"
  task :logs do
    puts "TODO"
  end

  desc "Clean up install files"
  task :install do
    cleanup_ssh_nopass
  end

end

desc "Configure single node"
task "config" do
  puts "TODO: Configure single node"
end

namespace :config do

  desc "Configure ssh-nopass"
  task "sshnopass" do
    ssh_nopass
  end

  desc "Configure network bridge"
  task "netbr" do
    ifname = nova_conf["vm_network_interface"]
    brname = nova_conf["vm_network_bridge"]
    puts "Creating bridge '#{brname}' on interface '#{ifname}'..."
    create_bridge ifname, brname
    puts "Done"
  end

  desc "Configure network forwarding"
  task "netfw" do
    puts "TODO"
# TODO update the netforwarding procedure
    all_nodes do |host, role|
      i = host[4..-1].to_i
      puts "iptables -t nat -A PREROUTING -d 166.111.131.32 -p tcp --dport #{4000 + i} -j DNAT --to-destination 10.0.5.#{i}:3000"
      puts "iptables -t nat -A POSTROUTING -d 10.0.5.#{i} -p tcp --dport 3000 -j SNAT --to 10.0.5.254"
    end

    puts "iptables -P FORWARD ACCEPT"
    puts "iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE"

    puts "iptables-save"

  end

end

task :status do
end

namespace :system do

  desc "Configure the system"
  task :config do
    gen_node_yaml
  end

  desc "Installs the whole system"
  task :install do
    addr = this_node["intranet_ip"]
    port = 50000 + rand(10000)
    puts "starting install server on #{addr}:#{port}"
    fork {
      sleep 1 # wait a few seconds
      sys_exec "ruby lib/install_client.rb --install-server=#{addr}:#{port}"
    }
    InstallServer.serve addr, port
  end

  desc "Start whole system"
  task :start do
    puts "TODO"
  end

  desc "Stop whole system"
  task :stop do
    puts "TODO"
  end

  desc "Update whole system"
  task :update do
      puts "Warning! If you have modified code, make sure the modification are already committed"
      puts "The update process will discard everything that is not committed!"
      puts "Please input: 'Yes I know what I am doing' to continue (' is not part of the input)"
      input = STDIN.gets.chomp
      if input != "Yes I know what I am doing"
	    puts "Update process is cancelled"
      else
	    # TODO update every node
	    git_update_this_node
      end
  end

  desc "!!!RESET WHOLE SYSTEM, BE CAREFUL!!!"
  task :reset do
    puts "TODO"
  end

  desc "Backup the whole system"
  task :backup do
    puts "TODO"
  end

end

task :default => :about
task :help => :about
