#! /bin/sh

NODELIST=$1
INSTLIST=$2
CONFIG_NAME=$3

if [ -z "$CONFIG_NAME" ]
then
	echo "Danger!"
	exit 1
fi

CONFIG_SOURCE=/config
SHARE_SOURCE=/share
MAPLIST=${CONFIG_SOURCE}/map.list

CONFIG_PATH=${CONFIG_SOURCE}/${CONFIG_NAME}
SHARE_PATH=${SHARE_SOURCE}/${CONFIG_NAME}

rm -rf ${CONFIG_PATH}
mkdir ${CONFIG_PATH}

cp ${NODELIST} ${CONFIG_PATH}/node.list
cp ${INSTLIST} ${CONFIG_PATH}/install.list

rm -rf ${SHARE_PATH}
mkdir ${SHARE_PATH}

while read APP
do
	echo "Processing $APP"
	mkdir ${SHARE_PATH}/${APP}
	mkdir ${SHARE_PATH}/${APP}/finished
done < ${INSTLIST}

while read IP NAME
do
	echo "Processing ${IP}"
	sed -e "/${IP}/d" -i ${MAPLIST}
	echo "${IP}	${CONFIG_NAME}" >> ${MAPLIST}
done < ${NODELIST}


