
require 'objective-j'
require 'objective-j/bundletask'

if !ENV['CONFIG']
    ENV['CONFIG'] = 'Debug'
end

ObjectiveJ::BundleTask.new(:webui) do |t|
    t.name          = 'Nova WebUI'
    t.identifier    = 'cn.edu.tsinghua.cs.hpcgrid.nova.webui'
    t.version       = '2.0'
    t.author        = 'Tsinghua University'
    t.email         = 'santa1987@gmail.com'
    t.summary       = 'webui'
    t.sources       = FileList['*.j']
    t.resources     = FileList['Resources/*']
    t.index_file    = 'index.html'
    t.info_plist    = 'Info.plist'
    t.build_path    = File.join('Build', ENV['CONFIG'], 'webui')
    t.flag          = '-DDEBUG' if ENV['CONFIG'] == 'Debug'
    t.flag          = '-O' if ENV['CONFIG'] == 'Release'
end

task :default => [:webui]
