#!/bin/sh

unset SERVER_ADDR
IPADDR=`ifconfig eth0 | grep "inet addr" | awk '{print $2}' | awk -F: '{print $2}'`
MASK=`ifconfig eth0 | grep Mask | awk '{print $4}' | awk -F: '{print $2}'`

unset TEMP
TEMP=""

for I in 1 2 3 4
do
	unset PARTA
	unset PARTB
	unset PARTC
	echo Processing ${I}
	PARTA=`echo ${IPADDR} | cut -d. -f${I}`
	PARTB=`echo ${MASK} | cut -d. -f${I}`

	PARTC=$((${PARTA} \& ${PARTB}))
	echo PARTA=${PARTA}
	echo PARTB=${PARTB}
	echo PARTC=${PARTC}

	if [ "$I" = "4" ]
	then
		PARTC=`expr ${PARTC} + 1`
	fi
	if [ ! -z "$TEMP" ]
	then
		TEMP="${TEMP}."
	fi
	TEMP="${TEMP}${PARTC}"

done

echo TEMP=${TEMP}
SERVER_ADDR=${TEMP}
echo SERVER_ADDR=${SERVER_ADDR}
exit 

echo IPADDR=${IPADDR}

NOTE=`date "+%Y%m%d%H%M"`

MAP_SOURCE=${SERVER_ADDR}:/config
MAP_PATH=/tmp/map_${NOTE}
MAPLIST=${MAP_PATH}/map.list

unset CONFIGURATION_NAME

rm -rf ${MAP_PATH}
mkdir ${MAP_PATH}

umount -f ${MAP_PATH}
mount ${MAP_SOURCE} ${MAP_PATH}

while read IP NAME
do
	echo IP=${IP},  CNAME=${NAME}
	if [ "${IP}" = "${IPADDR}" ]
	then
		CONFIGURATION_NAME=${NAME}
		break
	fi
done < ${MAPLIST}

umount -f ${MAP_PATH}

if [ -z "$CONFIGURATION_NAME" ]
then
	echo "Cannot find configuration for ${IPADDR}"
	exit 1
fi

/bin/sh vinst ${SERVER_ADDR} ${CONFIGURATION_NAME}
exit 0

